[pyprland]
hyprland_version = "0.49.0"
plugins = ["scratchpads"]

[scratchpads.yazi]
command = "kitty --class kitty-dropterm yazi"
class = "kitty-dropterm"                      # check: hyprctl clients | grep class
size = "90% 90%"                              # size of the window relative to the screen size
animation = "fromTop"

[scratchpads.spotify]
command = "spotify"
class = "Spotify"     # check: hyprctl clients | grep class
size = "90% 90%"      # size of the window relative to the screen size
animation = "fromTop"

[scratchpads.calculator]
command = "kitty --class kitty-dropterm ipython"
class = "kitty-dropterm"                         # check: hyprctl clients | grep class
size = "40% 80%"                                 # size of the window relative to the screen size
animation = "fromBottom"
